# Generated by Django 5.2.17 on 2026-09-18 16:49

import django.core.validators
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_team_structure_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(storage=recruitment.models.private_storage, upload_to='cvs/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Your CV must be a PDF.')]),
        ),
    ]
